apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: gnosis
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: api-gateway
          image: ap-mumbai-1.ocir.io/bmr6dpc3ujz4/gnosis/api-gateway:8d05bc9fee659b69c32836a801befb5ded582cd6
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: gnosis-secrets
            - configMapRef:
                name: gnosis-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
