apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: gnosis
  labels:
    app: notification-service
    project: gnosis
    monitoring: enabled
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 3006
      targetPort: 3006
      protocol: TCP
