apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gnosis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: frontend
          image: ap-mumbai-1.ocir.io/bmr6dpc3ujz4/gnosis/frontend:0c6b93d485159487b6ac6dec6cbf0fb36307846c
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
