apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: gnosis
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: auth-service
          image: ap-mumbai-1.ocir.io/bmr6dpc3ujz4/gnosis/auth-service:6a5ba555df71f6d8efa002c0cb4066b94e0d80bc
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: gnosis-secrets
            - configMapRef:
                name: gnosis-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
