apiVersion: v1
kind: Service
metadata:
  name: progress-service
  namespace: gnosis
  labels:
    app: progress-service
    project: gnosis
    monitoring: enabled
spec:
  type: ClusterIP
  selector:
    app: progress-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      protocol: TCP
