apiVersion: v1
kind: Service
metadata:
  name: battle-service
  namespace: gnosis
  labels:
    app: battle-service
    project: gnosis
    monitoring: enabled
spec:
  type: ClusterIP
  selector:
    app: battle-service
  ports:
    - name: http
      port: 3005
      targetPort: 3005
      protocol: TCP
