apiVersion: v1
kind: Service
metadata:
  name: xp-service
  namespace: gnosis
  labels:
    app: xp-service
    project: gnosis
    monitoring: enabled
spec:
  type: ClusterIP
  selector:
    app: xp-service
  ports:
    - name: http
      port: 3004
      targetPort: 3004
      protocol: TCP
