apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: gnosis
  labels:
    app: content-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3002"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: content-service
          image: ap-mumbai-1.ocir.io/bmr6dpc3ujz4/gnosis/content-service:c789aa1462293af0f18c907d5ccfeb264bbb0297
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: gnosis-secrets
            - configMapRef:
                name: gnosis-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
