apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: gnosis
  labels:
    app: content-service
    project: gnosis
    monitoring: enabled
spec:
  type: ClusterIP
  selector:
    app: content-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
